
sudo: required

language: node_js

node_js:
    - "9"

git:
    submodules: true
    
before_install:
    - sudo curl  -L http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.3 -o /usr/bin/upx
    - sudo chmod +x /usr/bin/upx
    - sudo npm install hexo-cli -g
        
install:
    - hexo generate
    
after_success:
    - upx login docs-notadds "BLOG" "$UPYUN"
    - upx put ./public   /
